# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6ac1b8b635e7cd61d8af55beb7ea238db309c1068f9fa782c8f960804ee6f73bde28fe4484b7f082bfa7a3eeb87a78badf4317f5c36f0141724e8cee81344a85

test:
  secret_key_base: ce82fcb68421e4cce1635581fada590f75ce5c8322b42dfd3983dbfc2b139af76be17338308f0496615706c3674bf406e19dc1fabc271f6d0075630e1b6d4c5d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
